# Sariah Kamore, financial_calculator, python

#print statement that welcomes user and tells what program it is.

#ask what their income is (variable an input)
income = float(input("what is your income?\n"))
#ask what their rent is (variable that is an input)
rent = float(input("what is your rent?\n"))
#ask what their untilites is (variable that is an input)
utilities = float(input("what are your utilities?\n"))
#ask what their groceries is (variable that is an input)
groceries = float(input("what is your groceries?\n"))
#ask what their transportation is (variable that is an input)
transportation = float(input("what is your transportation\n"))
#calculate savings as 10% of income (income*.1)
print ("Your savings is", income*.1)
#calculate spending as income-rent-utilities-groceries-transportaion-savings (variable)
print("Your spending is", income-rent-utilities-groceries-transportation-income*.1)
#calculate percent income of rent(rent/income*100) (variable)
#Your rent is $xx.xx which is xx% of your income. (print)
print("your rent is", rent, "which is", rent/income*100, "percent of your income")
#Your utilities is $xx.xx which is xx% of your income. (print)
print("your utilities is", utilities, "which is", utilities/income*100, "percent of your income")
#Your groceries is $xx.xx which is xx% of your income. (print)
print("your groceries is", groceries, "which is", groceries/income*100, "percent of your income")
#Your tansportation is $xx.xx which is xx% of your income. (print)
print("your transportation is", transportation, "which is", transportation/income*100, "percent of your income")
#Your savings is $xx.xx which is xx% of your income. (print)
print("your savings is", income*.1, "which is 10% of your income")
#Your spending is $xx.xx which is xx% of your income. (print)
print("your spending is", income-rent-utilities-groceries-transportation-income*.1, "which is", (income-rent-utilities-groceries-transportation-income*.1)/income*100, "percent of your income")
