# sariah kamore, variables practice python
name = input("put your name here: ")
subject = input("what is your favorite class:")
number = input("what is your favorite number between 1 and 10: ")
big_number =  input("what i your fvorite number between 100 and 1000:")
color = input("what is your favorite color:")
food = input("what was your breakfast: ")
school = input("what is the name of your school: ")
year = input("what year is it: ")
eye = input ("what is your eye color: ")
age = input("how old are you: ")
subject = input("what is your favorite subject: ")
print(name, "really likes", subject, "and the number", number, "and the number", big_number, "and the color", color, "and the food", food, "and the school", school, "and the year", year, "and the eye color", eye, "and the age", age, "and the subject", subject)